server:
  port: ${PORT:8861}

spring:
  application:
    name: auto-hub-service-discovery
  security:
    user:
      name: ${EUREKA_USER}
      password: ${EUREKA_PASSWORD}
  web:
    error:
      include-message: always
      include-binding-errors: never
      include-stacktrace: never
      include-exception: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
    status-page-url-path: http://localhost:8861/eureka/info
    health-check-url-path: http://localhost:8861/eureka/health
    secure-port-enabled: true
    non-secure-port-enabled: false
    secure-port: 8861
    prefer-ip-address: true
  server:
    wait-time-in-ms-when-sync-empty: 0

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          csrf:
            CsrfFilter: DEBUG
